[package]
name = "rwordle"
version = "0.1.0"
edition = "2021"

[dependencies]
bitvec = "1.0.1"
derive-new = "0.7.0"
hhmmss = "0.1.0"
itertools = "0.13.0"
rayon = "1.10.0"

[profile.release]
debug = true
